### ISSUE TITLE
List index out of range with Ruination Update

### ISSUE THREAD

**Issue by Ryuoftime** [colinhartigan/valorant-skin-cli#20]
![Error](https://user-images.githubusercontent.com/20760387/124997279-508a2600-e018-11eb-8252-8aa7493473ad.png)

Was working perfectly before purchasing the new skin bundle.

**Comment by RaySoyama** [comment]
![image](https://user-images.githubusercontent.com/42445829/125019494-04e17780-e02c-11eb-8fc5-960f46e6945a.png)
Bumping this. Crashing on startup.

**Comment by colinhartigan** [comment]
looking into this now, can one of you attach your `skincli.log` file? it's found in `%APPDATA%\valorant-skin-cli`

**Comment by RaySoyama** [comment]
[skincli.log](https://github.com/colinhartigan/valorant-skin-cli/files/6788905/skincli.log)
[skin_data.txt](https://github.com/colinhartigan/valorant-skin-cli/files/6788907/skin_data.txt)
Hope this helps

**Comment by colinhartigan** [comment]
i think i fixed the issue, try out [v1.0.1](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0.1)

**Comment by RaySoyama** [comment]
> i think i fixed the issue, try out [v1.0.1](https://github.com/colinhartigan/valorant-skin-cli/releases/tag/v1.0.1)

As of build v1.0.1, I can validate that it has resolved the issue. 

![image](https://user-images.githubusercontent.com/42445829/125030591-32382080-e040-11eb-861e-4235e28dc00b.png)


Semi-Related Feature Request: 
- Have the build number visible in the CLI on startup (maybe under the VALORANT-skin-cli title?)
- Not immediately close when the program asserts. (I had to use OBS to record the app crashing, and then scrub through frame frame in order to capture my original crash screen)
- If Valorant isn't open, and you open the CLI, it also immediately closes. If it could throw a loop where it checks if Valorant is open every 5 seconds, that would be nice.

**Comment by colinhartigan** [comment]
great ideas, i'll add these to the list

thanks for your help!
